// fixed: avoid global name conflict with Supabase CDN
'use strict';
const $ = id => document.getElementById(id);
const LS = 'drone_contact_rebuilt_v1_';
const REMOTE_KEYS = ['users','villages','visibleRounds','uploadHistory'];
const REMOTE_TABLE = 'app_state';
const REMOTE_ID = 'main';
let supabaseClient = null;
let remoteReady = false;
let remoteLoading = false;
let remoteSaveTimer = null;
let remoteSavePending = false;
let remoteChannel = null;
try {
  if (window.SAMJIN_SUPABASE && window.SAMJIN_SUPABASE.url && window.SAMJIN_SUPABASE.key && window.supabase) {
    supabaseClient = window.supabase.createClient(window.SAMJIN_SUPABASE.url, window.SAMJIN_SUPABASE.key);
  }
} catch (e) { console.error(e); }
const roundOrder = ['1차 방제','2차 방제','3차 방제'];
const townOrder = ['진전면','진북면','진동면','구산면','현동'];
const defaultUsers = [
  {id:'admin', name:'관리자', phone:'', password:'1234', role:'admin'},
  {id:'lee01', name:'이학준', phone:'', password:'1234', role:'worker'},
  {id:'kim01', name:'김철수', phone:'', password:'1234', role:'worker'},
  {id:'park01', name:'박영수', phone:'', password:'1234', role:'worker'}
];
const defaultVillages = [
  {id:'v001', eup:'진전면', village:'양촌마을', chief:'최성호', phone:'010-4444-4444'},
  {id:'v002', eup:'진전면', village:'오서마을', chief:'강민호', phone:'010-5555-1111'},
  {id:'v003', eup:'진북면', village:'이목마을', chief:'홍길동', phone:'010-1111-1111'},
  {id:'v004', eup:'진북면', village:'부산마을', chief:'김영수', phone:'010-2222-2222'},
  {id:'v005', eup:'진동면', village:'신촌마을', chief:'박민수', phone:'010-3333-3333'},
  {id:'v006', eup:'진동면', village:'태봉마을', chief:'정기호', phone:'010-5555-2222'},
  {id:'v007', eup:'구산면', village:'수정마을', chief:'이성민', phone:'010-5555-3333'},
  {id:'v008', eup:'현동', village:'현동마을', chief:'윤정호', phone:'010-5555-4444'}
];
let users = load('users', null) || importOldUsers() || defaultUsers;
let villages = (load('villages', null) || importOldVillages() || defaultVillages).map(migrateVillage);
let visibleRounds = load('visibleRounds', null) || [...roundOrder];
let uploadHistory = load('uploadHistory', null) || [];
let currentUser = load('currentUser', null);
let selectedRound = load('selectedRound', '');
let selectedTown = load('selectedTown', '');
let selectedVillageId = '';
let editingVillageId = '';
let editingUserId = '';
function load(k, fallback){ try{ const v = localStorage.getItem(LS+k); return v ? JSON.parse(v) : fallback; }catch(e){ return fallback; } }
function save(k, v){ localStorage.setItem(LS+k, JSON.stringify(v)); if(REMOTE_KEYS.includes(k)) scheduleRemoteSave(); }
function remoteSnapshot(){ return {users, villages, visibleRounds, uploadHistory, updatedAt: new Date().toISOString()}; }
function applyRemoteSnapshot(data){ if(!data || typeof data !== 'object') return; if(Array.isArray(data.users)) users = data.users; if(Array.isArray(data.villages)) villages = data.villages.map(migrateVillage); if(Array.isArray(data.visibleRounds)) visibleRounds = data.visibleRounds; if(Array.isArray(data.uploadHistory)) uploadHistory = data.uploadHistory; localStorage.setItem(LS+'users', JSON.stringify(users)); localStorage.setItem(LS+'villages', JSON.stringify(villages)); localStorage.setItem(LS+'visibleRounds', JSON.stringify(visibleRounds)); localStorage.setItem(LS+'uploadHistory', JSON.stringify(uploadHistory)); }
function scheduleRemoteSave(){ if(!supabaseClient || !remoteReady || remoteLoading) return; remoteSavePending = true; clearTimeout(remoteSaveTimer); remoteSaveTimer = setTimeout(saveRemoteNow, 350); }
async function saveRemoteNow(){ if(!supabaseClient || !remoteReady || !remoteSavePending || remoteLoading) return; remoteSavePending = false; const payload = remoteSnapshot(); const { error } = await supabaseClient.from(REMOTE_TABLE).upsert({ id: REMOTE_ID, data: payload, updated_at: new Date().toISOString() }); if(error) showError('실시간 저장 오류: '+error.message); }
async function loadRemoteState(){ if(!supabaseClient) return; remoteLoading = true; const { data, error } = await supabaseClient.from(REMOTE_TABLE).select('data').eq('id', REMOTE_ID).maybeSingle(); if(error){ remoteLoading = false; showError('Supabase 연결 오류: '+error.message); return; } if(data && data.data){ applyRemoteSnapshot(data.data); } else { await supabaseClient.from(REMOTE_TABLE).upsert({ id: REMOTE_ID, data: remoteSnapshot(), updated_at: new Date().toISOString() }); } remoteReady = true; remoteLoading = false; }
function subscribeRemote(){ if(!supabaseClient || remoteChannel) return; remoteChannel = supabaseClient.channel('samjin-app-state').on('postgres_changes', {event:'*', schema:'public', table:REMOTE_TABLE, filter:'id=eq.'+REMOTE_ID}, payload=>{ if(payload && payload.new && payload.new.data){ remoteLoading = true; applyRemoteSnapshot(payload.new.data); remoteLoading = false; render(); } }).subscribe(); }
function showError(msg){ const el=$('errorBox'); if(!el) return; el.classList.remove('hidden'); el.textContent=msg; }
function importOldUsers(){ try{ const x = JSON.parse(localStorage.getItem('users') || 'null'); return Array.isArray(x) ? x : null; }catch(e){ return null; } }
function importOldVillages(){ try{ const x = JSON.parse(localStorage.getItem('villages') || 'null'); return Array.isArray(x) ? x : null; }catch(e){ return null; } }
function blank(){ return {status:'pending', completedBy:'', completedAt:'', completedList:[], note:'', noteBy:'', noteAt:'', noteImportant:false, history:[]}; }
function migrateVillage(v){
  const base = {id:v.id || uid(), eup:v.eup || '진전면', village:v.village || '', chief:v.chief || '', phone:v.phone || '', chiefHistory:Array.isArray(v.chiefHistory)?v.chiefHistory:[]};
  base.rounds = v.rounds && typeof v.rounds === 'object' ? v.rounds : {};
  roundOrder.forEach(r=>{ if(!base.rounds[r]) base.rounds[r] = blank(); if(!Array.isArray(base.rounds[r].history)) base.rounds[r].history = []; if(!Array.isArray(base.rounds[r].completedList)) base.rounds[r].completedList = base.rounds[r].completedBy ? [{user:base.rounds[r].completedBy, at:base.rounds[r].completedAt || '', canceled:false}] : []; if(base.rounds[r].noteImportant===undefined) base.rounds[r].noteImportant=false; syncContactSummary(base.rounds[r]); });
  if(v.status || v.completedBy || v.note){ Object.assign(base.rounds['1차 방제'], {status:v.status||'pending', completedBy:v.completedBy||'', completedAt:v.completedAt||'', completedList:v.completedBy?[{user:v.completedBy, at:v.completedAt||''}]:[], note:v.note||'', noteBy:v.noteBy||'', noteAt:v.noteAt||'', history:Array.isArray(v.history)?v.history:[]}); }
  return base;
}
function persistAll(){ save('users', users); save('villages', villages); save('visibleRounds', visibleRounds); save('uploadHistory', uploadHistory); if(currentUser) save('currentUser', currentUser); }
function uid(){ return 'v' + Date.now() + Math.random().toString(36).slice(2,7); }
function safe(s){ return String(s ?? '').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function norm(s){ return String(s||'').trim().toLowerCase().replace(/\s+/g,''); }
function now(){ return new Date().toLocaleString('ko-KR', {hour12:false}); }
function activeRound(){ return selectedRound || visibleRounds[0] || roundOrder[0]; }
function rec(v, round=activeRound()){ if(!v.rounds) v.rounds={}; if(!v.rounds[round]) v.rounds[round]=blank(); return v.rounds[round]; }

function allContactEntries(r){ if(!Array.isArray(r.completedList)) r.completedList = r.completedBy ? [{user:r.completedBy, at:r.completedAt || '', canceled:false}] : []; return r.completedList; }
function activeContactEntries(r){ return allContactEntries(r).filter(x=>!x.canceled); }
function contactEntries(r){ return activeContactEntries(r); }
function contactNames(r){ const names=[...new Set(activeContactEntries(r).map(x=>x.user).filter(Boolean))]; return names.join(', '); }
function lastContactAt(r){ const list=activeContactEntries(r); return list.length ? (list[list.length-1].at || '') : ''; }
function syncContactSummary(r){ const names=contactNames(r); r.completedBy=names; r.completedAt=lastContactAt(r); r.status=names ? 'done' : 'pending'; }
function changeChief(v, newChief, newPhone, source){ const oldChief=v.chief||'', oldPhone=v.phone||''; const chiefChanged=oldChief!==newChief, phoneChanged=oldPhone!==newPhone; if((chiefChanged||phoneChanged) && (oldChief||oldPhone)){ if(!Array.isArray(v.chiefHistory)) v.chiefHistory=[]; v.chiefHistory.unshift({at:now(), user:currentUser?currentUser.name:'-', source:source||'수정', oldChief, newChief, oldPhone, newPhone, text:`${source||'수정'}: ${oldChief||'-'} → ${newChief||'-'} / ${oldPhone||'-'} → ${newPhone||'-'}`}); } v.chief=newChief; v.phone=newPhone; }
function isImportantNote(r){ const t=String(r.note||''); return !!r.noteImportant || /(민원|주의|이장\s*변경|전화\s*안\s*받|부재|오후|오전|불가|금지|행사|위험|진입)/.test(t); }

function visible(){ return roundOrder.filter(r=>visibleRounds.includes(r)); }
function towns(){ const set = new Set(villages.map(v=>v.eup)); return [...townOrder.filter(t=>set.has(t)), ...[...set].filter(t=>!townOrder.includes(t)).sort((a,b)=>a.localeCompare(b,'ko'))]; }
async function init(){
  $('todayText').textContent = new Date().toLocaleDateString('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'long'});
  bind();
  if(supabaseClient){ await loadRemoteState(); subscribeRemote(); } else { showError('Supabase 설정이 없습니다. config.js에 URL과 Publishable Key를 입력하세요. 현재는 이 기기 안에서만 저장됩니다.'); }
  persistAll(); render();
}
function bind(){
  $('loginBtn').onclick = login; $('logoutBtn').onclick = logout; $('showSignupBtn').onclick = ()=>showAuth('signup'); $('showPasswordResetBtn').onclick = ()=>showAuth('reset'); $('backLoginBtn').onclick=()=>showAuth('login'); $('backLoginFromResetBtn').onclick=()=>showAuth('login'); $('signupBtn').onclick=signup; $('resetPasswordBtn').onclick=resetPassword;
  $('contactTab').onclick=()=>showPage('contact'); $('adminTab').onclick=()=>showPage('admin'); $('searchInput').oninput=renderContact; $('statusFilter').onchange=renderContact; $('pendingOnlyBtn').onclick=()=>{ $('statusFilter').value='pending'; renderContact(); }; 
  $('backToRoundsBtn').onclick=()=>{selectedRound='';selectedTown='';save('selectedRound','');save('selectedTown','');renderContact();};
  $('backToTownsBtn').onclick=()=>{selectedTown='';save('selectedTown','');renderContact();};
  $('roundList').onclick=e=>{ const card=e.target.closest('[data-round]'); if(card) {selectedRound=card.dataset.round; selectedTown=''; save('selectedRound',selectedRound); save('selectedTown',''); renderContact();} };
  $('townList').onclick=e=>{ const card=e.target.closest('[data-town]'); if(card) {selectedTown=card.dataset.town; save('selectedTown',selectedTown); renderContact();} };
  $('villageList').onclick=e=>{ const card=e.target.closest('[data-village]'); if(card) openVillage(card.dataset.village); };
  $('closeDialogBtn').onclick=()=>{$('villageDialog').close();}; $('completeBtn').onclick=completeContact; $('saveNoteBtn').onclick=saveNote; $('contactHistoryList').onclick=e=>{ const btn=e.target.closest('[data-cancel-contact]'); if(btn) cancelContact(btn.dataset.cancelContact); };
  $('saveRoundVisibilityBtn').onclick=saveRoundVisibility; $('saveVillageBtn').onclick=saveVillage; $('clearVillageFormBtn').onclick=clearVillageForm; $('saveUserBtn').onclick=saveUser; $('clearUserFormBtn').onclick=clearUserForm; $('importVillageBtn').onclick=importVillageFile; $('downloadTemplateBtn').onclick=downloadVillageTemplate; $('exportVillageBtn').onclick=exportVillages;
  $('villageTable').onclick=e=>{ const edit=e.target.closest('[data-edit-village]'); const del=e.target.closest('[data-delete-village]'); if(edit) editVillage(edit.dataset.editVillage); if(del) deleteVillage(del.dataset.deleteVillage); };
  $('userTable').onclick=e=>{ const edit=e.target.closest('[data-edit-user]'); const del=e.target.closest('[data-delete-user]'); if(edit) editUser(edit.dataset.editUser); if(del) deleteUser(del.dataset.deleteUser); };
}
function showAuth(mode){ $('loginSection').classList.toggle('hidden', mode!=='login'); $('signupSection').classList.toggle('hidden', mode!=='signup'); $('passwordResetSection').classList.toggle('hidden', mode!=='reset'); }
function resetPassword(){ const id=norm($('resetId').value); const phone=norm($('resetPhone').value); const pw=$('resetPw').value; const pw2=$('resetPw2').value; if(!id||!phone||!pw) return alert('아이디, 연락처, 새 비밀번호를 입력하세요.'); if(pw!==pw2) return alert('새 비밀번호가 서로 다릅니다.'); const u=users.find(x=>norm(x.id)===id && norm(x.phone)===phone); if(!u) return alert('아이디와 가입 연락처가 일치하는 계정을 찾지 못했습니다. 관리자에게 문의하세요.'); u.password=pw; save('users',users); ['resetId','resetPhone','resetPw','resetPw2'].forEach(id=>$(id).value=''); $('loginId').value=u.id; $('loginPw').value=''; showAuth('login'); alert('비밀번호가 변경되었습니다. 새 비밀번호로 로그인하세요.'); }
function login(){ const id=norm($('loginId').value); const pw=$('loginPw').value; const u=users.find(x=>norm(x.id)===id && x.password===pw); if(!u) return alert('아이디 또는 비밀번호가 맞지 않습니다.'); currentUser={id:u.id,name:u.name,phone:u.phone||'',role:u.role}; save('currentUser', currentUser); render(); }
function logout(){ currentUser=null; selectedRound=''; selectedTown=''; ['currentUser','selectedRound','selectedTown'].forEach(k=>localStorage.removeItem(LS+k)); render(); }
function signup(){ const name=$('signupName').value.trim(), id=norm($('signupId').value), phone=$('signupPhone').value.trim(), pw=$('signupPw').value; if(!name||!id||!pw) return alert('이름, 아이디, 비밀번호를 입력하세요.'); if(users.some(u=>norm(u.id)===id)) return alert('이미 사용 중인 아이디입니다.'); users.push({id,name,phone,password:pw,role:'worker'}); save('users',users); $('loginId').value=id; $('loginPw').value=pw; ['signupName','signupId','signupPhone','signupPw'].forEach(id=>$(id).value=''); showAuth('login'); alert('가입되었습니다.'); }
function render(){ const logged=!!currentUser; $('loginSection').classList.toggle('hidden',logged); $('signupSection').classList.add('hidden'); $('passwordResetSection').classList.add('hidden'); $('appSection').classList.toggle('hidden',!logged); $('logoutBtn').classList.toggle('hidden',!logged); $('userBadge').classList.toggle('hidden',!logged); if(logged){ $('userBadge').textContent=`${currentUser.name} · ${currentUser.role==='admin'?'관리자':'방제사'}`; $('adminTab').classList.toggle('hidden', currentUser.role!=='admin'); renderContact(); renderAdmin(); } }
function showPage(page){ if(page==='admin'&&currentUser.role!=='admin') page='contact'; $('contactPage').classList.toggle('hidden',page!=='contact'); $('adminPage').classList.toggle('hidden',page!=='admin'); $('contactTab').classList.toggle('active',page==='contact'); $('adminTab').classList.toggle('active',page==='admin'); if(page==='admin') renderAdmin(); }
function filteredVillages(){ const q=$('searchInput').value.trim(); const f=$('statusFilter').value; return villages.filter(v=>{ const r=rec(v); const text=`${v.eup} ${v.village} ${v.chief} ${v.phone} ${contactNames(r)} ${r.note}`; return (!q||text.includes(q)) && (f==='all'||(f==='pending'&&r.status!=='done')||(f==='done'&&r.status==='done')||(f==='note'&&r.note)||(f==='important'&&isImportantNote(r))); }); }
function stats(list=villages, round=activeRound()){ const total=list.length, done=list.filter(v=>contactEntries(rec(v,round)).length>0).length, note=list.filter(v=>rec(v,round).note).length; return {total,done,pending:total-done,note,rate:total?Math.round(done/total*100):0}; }
function renderSummary(){ const s=stats(); $('totalCount').textContent=s.total; $('doneCount').textContent=s.done; $('pendingCount').textContent=s.pending; $('rateText').textContent=s.rate+'%'; }
function renderContact(){ if(selectedRound && !visible().includes(selectedRound)){ selectedRound=''; selectedTown=''; } renderSummary(); if(!selectedRound) return renderRoundView(); if(!selectedTown) return renderTownView(); return renderVillageView(); }
function renderRoundView(){ $('roundView').classList.remove('hidden'); $('townView').classList.add('hidden'); $('villageView').classList.add('hidden'); $('breadcrumb').classList.add('hidden'); const list=visible(); $('roundList').innerHTML=list.length?list.map(r=>{ const s=stats(villages,r); return `<article class="card town-card" data-round="${safe(r)}"><div class="town-name">${safe(r)}</div><div class="town-stats"><span class="badge done">완료 ${s.done}</span><span class="badge pending">미연락 ${s.pending}</span>${s.note?`<span class="badge note">특이사항 ${s.note}</span>`:''}</div><div class="progress"><span style="width:${s.rate}%"></span></div><div class="meta">전체 ${s.total}개 마을 · 완료율 ${s.rate}%</div></article>`; }).join(''):'<div class="card">관리자가 공개한 차수가 없습니다.</div>'; }
function notePreviewForTown(t){ const notes=villages.filter(v=>v.eup===t).map(v=>({v,r:rec(v)})).filter(x=>x.r.note).slice(0,3); if(!notes.length) return ''; return `<div class="note-preview-list">${notes.map(x=>`<div class="note-preview-row ${isImportantNote(x.r)?'important':''}"><strong>${safe(x.v.village)}</strong> ${safe(x.r.note)}</div>`).join('')}${stats(villages.filter(v=>v.eup===t)).note>3?'<div class="meta">외 특이사항 더 있음</div>':''}</div>`; }
function renderTownView(){ $('roundView').classList.add('hidden'); $('townView').classList.remove('hidden'); $('villageView').classList.add('hidden'); $('breadcrumb').classList.remove('hidden'); $('breadcrumb').textContent=selectedRound; const fv=filteredVillages(); $('townList').innerHTML=towns().map(t=>{ const list=villages.filter(v=>v.eup===t), shown=fv.filter(v=>v.eup===t), s=stats(list); return `<article class="card town-card" data-town="${safe(t)}"><div class="town-name">${safe(t)}</div><div class="town-stats"><span class="badge done">완료 ${s.done}</span><span class="badge pending">미연락 ${s.pending}</span>${s.note?`<span class="badge note">특이사항 ${s.note}</span>`:''}</div><div class="progress"><span style="width:${s.rate}%"></span></div><div class="meta">전체 ${s.total}개 마을 · 완료율 ${s.rate}%${shown.length!==list.length?` · 검색결과 ${shown.length}개`:''}</div>${notePreviewForTown(t)}</article>`; }).join('') || '<div class="card">등록된 마을이 없습니다.</div>'; }
function renderVillageView(){ $('roundView').classList.add('hidden'); $('townView').classList.add('hidden'); $('villageView').classList.remove('hidden'); $('breadcrumb').classList.remove('hidden'); $('breadcrumb').textContent=`${selectedRound} > ${selectedTown}`; const all=villages.filter(v=>v.eup===selectedTown), s=stats(all); $('selectedTownTitle').textContent=selectedTown; $('selectedTownDesc').textContent=`전체 ${s.total}개 · 완료 ${s.done} · 미연락 ${s.pending} · 특이사항 ${s.note} · 완료율 ${s.rate}%`; const list=filteredVillages().filter(v=>v.eup===selectedTown); $('villageList').innerHTML=list.length?list.map(v=>{ const r=rec(v); return `<article class="card village-card" data-village="${safe(v.id)}"><div class="village-title"><strong>${safe(v.village)}</strong><span class="badge ${r.status==='done'?'done':'pending'}">${r.status==='done'?'완료':'미연락'}</span></div><div class="chief">이장님: ${safe(v.chief)}</div><div class="meta">연락처: ${safe(v.phone)}</div><div class="meta">담당 방제사: ${safe(contactNames(r)||'연락 전')}</div>${lastContactAt(r)?`<div class="meta">최근 연락 완료: ${safe(lastContactAt(r))}</div>`:''}${r.note?`<div class="note-card ${isImportantNote(r)?'important':''}"><div class="note-card-title">${isImportantNote(r)?'중요 특이사항':'특이사항'}</div><div>${safe(r.note)}</div><div class="meta">작성: ${safe(r.noteBy||'-')} · ${safe(r.noteAt||'-')}</div></div>`:''}</article>`; }).join(''):'<div class="card">조건에 맞는 마을이 없습니다.</div>'; }
function openVillage(id){ const v=villages.find(x=>x.id===id); if(!v) return; selectedVillageId=id; const r=rec(v); $('dialogTitle').textContent=`${selectedRound} · ${v.eup} ${v.village}`; $('dialogSub').textContent=`담당 방제사: ${contactNames(r)||'연락 전'}`; $('chiefName').textContent=v.chief; $('chiefPhone').textContent=v.phone; $('assignedDisplay').textContent=contactNames(r)||'연락 전'; $('callBtn').href='tel:'+v.phone.replace(/[^0-9]/g,''); $('noteInput').value=r.note||''; $('noteImportantCheck').checked=!!r.noteImportant; drawDialog(v); $('villageDialog').showModal(); }
function drawDialog(v){
  const r=rec(v);
  syncContactSummary(r);
  $('statusBox').innerHTML=r.status==='done'?`<strong>연락 완료</strong><br>${safe(r.completedBy)} / ${safe(r.completedAt)}`:'<strong>아직 연락 전입니다.</strong>';
  $('dialogSub').textContent=`담당 방제사: ${contactNames(r)||'연락 전'}`;
  $('assignedDisplay').textContent=contactNames(r)||'연락 전';
  const contacts=[];
  roundOrder.forEach(round=>{
    const rr=rec(v,round);
    allContactEntries(rr).forEach((c,i)=>contacts.push({round, index:i, ...c}));
  });
  $('contactHistoryList').innerHTML=contacts.length?contacts.reverse().map(c=>`<div class="history-item ${c.canceled?'canceled':''}"><strong>${safe(c.round)} · ${c.canceled?'연락완료 취소':'연락완료'}</strong> - ${safe(c.user)}<time>${safe(c.at||'-')}</time>${c.canceled?`<div class="danger-text">취소: ${safe(c.cancelBy||'-')} · ${safe(c.cancelAt||'-')} · ${safe(c.cancelReason||'사유 없음')}</div>`:''}${(!c.canceled && currentUser.role==='admin')?`<button class="mini danger" data-cancel-contact="${safe(c.round)}|${c.index}">연락완료 취소</button>`:''}</div>`).join(''):'<p class="muted">아직 연락완료 이력이 없습니다.</p>';
  const chiefLogs=(v.chiefHistory||[]).map(x=>({type:'이장 변경',user:x.user,at:x.at,text:x.text||`${x.oldChief||'-'} → ${x.newChief||'-'}`}));
  const h=[...(r.history||[]), ...chiefLogs].sort((a,b)=>String(b.at).localeCompare(String(a.at),'ko'));
  $('historyList').innerHTML=h.length?h.map(x=>`<div class="history-item"><strong>${safe(x.type)}</strong> - ${safe(x.user)}<time>${safe(x.at)}</time><div>${safe(x.text||'')}</div></div>`).join(''):'<p class="muted">아직 기록이 없습니다.</p>';
}
function completeContact(){ const v=villages.find(x=>x.id===selectedVillageId); if(!v) return alert('마을을 다시 선택하세요.'); const r=rec(v); const at=now(); const list=allContactEntries(r); if(activeContactEntries(r).some(x=>x.userId===currentUser.id)){ return alert('이미 이 차수에서 연락완료 기록이 있습니다. 추가 연락자는 다른 계정으로 기록해 주세요.'); } list.push({user:currentUser.name, userId:currentUser.id, role:currentUser.role, at, canceled:false}); syncContactSummary(r); r.history.push({type:'연락 완료',user:currentUser.name,at,text:`${selectedRound} / ${v.eup} ${v.village} / 담당 추가: ${currentUser.name}`}); save('villages',villages); drawDialog(v); renderContact(); alert('연락완료가 기록되었습니다.'); }
function cancelContact(key){ if(currentUser.role!=='admin') return alert('관리자만 연락완료를 취소할 수 있습니다.'); const [round, idxText]=String(key).split('|'); const idx=Number(idxText); const v=villages.find(x=>x.id===selectedVillageId); if(!v) return alert('마을을 다시 선택하세요.'); const r=rec(v,round); const item=allContactEntries(r)[idx]; if(!item || item.canceled) return alert('취소할 연락완료 기록을 찾지 못했습니다.'); const reason=prompt('취소 사유를 입력하세요.', '잘못 누름') || '사유 미입력'; item.canceled=true; item.cancelBy=currentUser.name; item.cancelAt=now(); item.cancelReason=reason; syncContactSummary(r); r.history.push({type:'연락완료 취소',user:currentUser.name,at:item.cancelAt,text:`${round} / ${v.eup} ${v.village} / ${item.user} 기록 취소 / ${reason}`}); save('villages',villages); drawDialog(v); renderContact(); alert('취소 이력으로 기록되었습니다.'); }
function saveNote(){ const v=villages.find(x=>x.id===selectedVillageId); if(!v) return alert('마을을 다시 선택하세요.'); const r=rec(v), text=$('noteInput').value.trim(), important=$('noteImportantCheck').checked; if(r.note && currentUser.role!=='admin' && r.noteBy!==currentUser.name) return alert('특이사항은 작성자 또는 관리자만 수정할 수 있습니다.'); if(r.note!==text || !!r.noteImportant!==!!important){ r.note=text; r.noteImportant=!!important; r.noteBy=text?currentUser.name:''; r.noteAt=text?now():''; r.history.push({type:important?'중요 특이사항 저장':'특이사항 저장',user:currentUser.name,at:now(),text:text||'내용 삭제'}); save('villages',villages); } drawDialog(v); renderContact(); alert('저장되었습니다.'); }

function cleanHeader(h){ return String(h||'').trim().replace(/\s+/g,''); }
function pick(row, names){ for(const n of names){ if(row[n]!==undefined && row[n]!==null && String(row[n]).trim()!=='') return String(row[n]).trim(); } return ''; }
function normalizeVillageRow(row){ const m={}; Object.keys(row).forEach(k=>m[cleanHeader(k)]=row[k]); const eup=pick(m,['읍면','면','지역','행정구역']); const village=pick(m,['마을명','마을','리','동리','법정리']); const chief=pick(m,['이장명','이장님','이장','성명','이름']); const phone=pick(m,['연락처','이장연락처','전화번호','휴대폰','핸드폰']); if(!eup||!village||!chief||!phone) return null; return {eup, village, chief, phone}; }
function parseCsv(text){ const rows=[]; let row=[], cell='', q=false; for(let i=0;i<text.length;i++){ const c=text[i], n=text[i+1]; if(c==='"'){ if(q&&n==='"'){cell+='"';i++;} else q=!q; } else if((c===','||c==='\t')&&!q){ row.push(cell); cell=''; } else if((c==='\n'||c==='\r')&&!q){ if(c==='\r'&&n==='\n') i++; row.push(cell); if(row.some(x=>String(x).trim()!=='')) rows.push(row); row=[]; cell=''; } else cell+=c; } row.push(cell); if(row.some(x=>String(x).trim()!=='')) rows.push(row); if(!rows.length) return []; const headers=rows.shift().map(cleanHeader); return rows.map(r=>{ const o={}; headers.forEach((h,i)=>o[h]=r[i]||''); return o; }); }
function rowsFromWorkbook(wb){ const sheet=wb.Sheets[wb.SheetNames[0]]; return XLSX.utils.sheet_to_json(sheet,{defval:''}); }
function readVillageFile(file){ return new Promise((resolve,reject)=>{ const ext=file.name.split('.').pop().toLowerCase(); const reader=new FileReader(); reader.onerror=()=>reject(new Error('파일을 읽을 수 없습니다.')); if(['xlsx','xls'].includes(ext)){ reader.onload=e=>{ try{ if(typeof XLSX==='undefined') throw new Error('엑셀 파일을 읽는 라이브러리를 불러오지 못했습니다. 인터넷 연결이 안 되면 CSV로 저장 후 업로드해 주세요.'); const wb=XLSX.read(new Uint8Array(e.target.result),{type:'array'}); resolve(rowsFromWorkbook(wb)); }catch(err){ reject(err); } }; reader.readAsArrayBuffer(file); } else { reader.onload=e=>{ try{ resolve(parseCsv(e.target.result)); }catch(err){ reject(err); } }; reader.readAsText(file,'utf-8'); } }); }
async function importVillageFile(){ try{ const input=$('villageFileInput'); const file=input.files && input.files[0]; if(!file) return alert('업로드할 파일을 선택하세요.'); $('importStatus').textContent='파일을 읽는 중입니다...'; const raw=await readVillageFile(file); const rows=raw.map(normalizeVillageRow).filter(Boolean); if(!rows.length){ $('importStatus').textContent='등록 가능한 행이 없습니다. 양식의 열 이름을 확인하세요.'; return alert('등록 가능한 행이 없습니다. 열 이름은 읍면, 마을명, 이장명, 연락처를 사용해 주세요.'); }
    const overwrite=$('overwriteVillageCheck').checked; let added=0, updated=0, skipped=0; rows.forEach(row=>{ const idx=villages.findIndex(v=>norm(v.eup)===norm(row.eup)&&norm(v.village)===norm(row.village)); if(idx>=0){ if(overwrite){ changeChief(villages[idx], row.chief, row.phone, '엑셀 업로드'); updated++; } else skipped++; } else { villages.push(migrateVillage({id:uid(),eup:row.eup,village:row.village,chief:row.chief,phone:row.phone})); added++; } }); const hist={at:now(), user:currentUser?currentUser.name:'-', file:file.name, total:rows.length, added, updated, skipped}; uploadHistory.unshift(hist); save('villages',villages); save('uploadHistory',uploadHistory); input.value=''; $('importStatus').textContent=`업로드 완료: 신규 ${added}건, 수정 ${updated}건, 건너뜀 ${skipped}건`; renderContact(); renderAdmin(); alert(`이장 리스트 업로드 완료\n신규 ${added}건 / 수정 ${updated}건 / 건너뜀 ${skipped}건`); }catch(err){ console.error(err); $('importStatus').textContent='업로드 오류: '+err.message; alert('업로드 중 오류가 발생했습니다. '+err.message); } }
function csvCell(v){ const s=String(v??''); return /[",\n\t]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s; }
function downloadCsv(filename, rows){ const csv=rows.map(r=>r.map(csvCell).join(',')).join('\n'); const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=filename; document.body.appendChild(a); a.click(); setTimeout(()=>{URL.revokeObjectURL(a.href); a.remove();},0); }
function downloadVillageTemplate(){ downloadCsv('이장리스트_업로드양식.csv', [['읍면','마을명','이장명','연락처'], ['진북면','이목마을','홍길동','010-0000-0000']]); }
function exportVillages(){ const rows=[['읍면','마을명','이장명','연락처','등록ID']].concat(villages.map(v=>[v.eup,v.village,v.chief,v.phone,v.id])); downloadCsv('현재_이장리스트.csv', rows); }
function renderUploadHistory(){ const el=$('uploadHistoryTable'); if(!el) return; el.innerHTML=`<table><thead><tr><th>업로드 일시</th><th>업로드 관리자</th><th>파일명</th><th>총 행</th><th>신규</th><th>수정</th><th>건너뜀</th></tr></thead><tbody>${uploadHistory.map(h=>`<tr><td>${safe(h.at)}</td><td>${safe(h.user)}</td><td>${safe(h.file)}</td><td>${safe(h.total)}</td><td>${safe(h.added)}</td><td>${safe(h.updated)}</td><td>${safe(h.skipped)}</td></tr>`).join('')||'<tr><td colspan="7">아직 업로드 이력이 없습니다.</td></tr>'}</tbody></table>`; }

function renderAdmin(){ if(!currentUser || currentUser.role!=='admin') return; $('roundVisibilityList').innerHTML=roundOrder.map(r=>`<label><input type="checkbox" value="${safe(r)}" ${visibleRounds.includes(r)?'checked':''}> ${safe(r)}</label>`).join(''); $('roundVisibilityStatus').textContent='현재 공개: '+(visible().join(', ')||'없음'); renderUploadHistory(); renderChiefChangeHistory(); renderVillageTable(); renderUserTable(); }
function saveRoundVisibility(){ visibleRounds=[...$('roundVisibilityList').querySelectorAll('input:checked')].map(x=>x.value); save('visibleRounds',visibleRounds); if(selectedRound&&!visible().includes(selectedRound)){selectedRound='';selectedTown='';save('selectedRound','');save('selectedTown','');} renderContact(); renderAdmin(); alert('저장되었습니다.'); }
function renderChiefChangeHistory(){ const el=$('chiefChangeHistoryTable'); if(!el) return; const logs=[]; villages.forEach(v=>(v.chiefHistory||[]).forEach(h=>logs.push({...h,eup:v.eup,village:v.village}))); logs.sort((a,b)=>String(b.at).localeCompare(String(a.at),'ko')); el.innerHTML=`<table><thead><tr><th>변경 일시</th><th>읍면</th><th>마을</th><th>변경 내용</th><th>처리자</th><th>출처</th></tr></thead><tbody>${logs.map(h=>`<tr><td>${safe(h.at)}</td><td>${safe(h.eup)}</td><td>${safe(h.village)}</td><td>${safe(h.oldChief||'-')} → ${safe(h.newChief||'-')}<br><span class="muted">${safe(h.oldPhone||'-')} → ${safe(h.newPhone||'-')}</span></td><td>${safe(h.user)}</td><td>${safe(h.source||'-')}</td></tr>`).join('')||'<tr><td colspan="6">아직 이장 변경 이력이 없습니다.</td></tr>'}</tbody></table>`; }
function renderVillageTable(){ $('villageTable').innerHTML=`<table><thead><tr><th>읍면</th><th>마을</th><th>이장님</th><th>연락처</th><th>연락자</th><th>관리</th></tr></thead><tbody>${villages.map(v=>`<tr><td>${safe(v.eup)}</td><td>${safe(v.village)}</td><td>${safe(v.chief)}</td><td>${safe(v.phone)}</td><td>${roundOrder.map(r=>`${r}: ${contactNames(rec(v,r))||'-'}`).join('<br>')}</td><td><button class="mini secondary" data-edit-village="${safe(v.id)}">수정</button> <button class="mini danger" data-delete-village="${safe(v.id)}">삭제</button></td></tr>`).join('')||'<tr><td colspan="6">등록된 마을이 없습니다.</td></tr>'}</tbody></table>`; }
function saveVillage(){ const eup=$('adminEup').value.trim(), village=$('adminVillage').value.trim(), chief=$('adminChief').value.trim(), phone=$('adminPhone').value.trim(); if(!eup||!village||!chief||!phone) return alert('읍면, 마을명, 이장님 성함, 연락처를 입력하세요.'); if(editingVillageId){ const v=villages.find(x=>x.id===editingVillageId); v.eup=eup; v.village=village; changeChief(v, chief, phone, '관리자 직접 수정'); } else villages.push(migrateVillage({id:uid(),eup,village,chief,phone})); save('villages',villages); clearVillageForm(); renderContact(); renderAdmin(); alert('저장되었습니다.'); }
function editVillage(id){ const v=villages.find(x=>x.id===id); if(!v) return; editingVillageId=id; $('adminEup').value=v.eup; $('adminVillage').value=v.village; $('adminChief').value=v.chief; $('adminPhone').value=v.phone; window.scrollTo({top:0,behavior:'smooth'}); }
function deleteVillage(id){ const v=villages.find(x=>x.id===id); if(v&&confirm(`${v.eup} ${v.village}을 삭제할까요?`)){ villages=villages.filter(x=>x.id!==id); save('villages',villages); renderContact(); renderAdmin(); } }
function clearVillageForm(){ editingVillageId=''; $('adminEup').value='진전면'; ['adminVillage','adminChief','adminPhone'].forEach(id=>$(id).value=''); }
function renderUserTable(){ $('userTable').innerHTML=`<table><thead><tr><th>이름</th><th>아이디</th><th>연락처</th><th>권한</th><th>관리</th></tr></thead><tbody>${users.map(u=>`<tr><td>${safe(u.name)}</td><td>${safe(u.id)}</td><td>${safe(u.phone||'-')}</td><td>${u.role==='admin'?'관리자':'방제사'}</td><td><button class="mini secondary" data-edit-user="${safe(u.id)}">수정</button> <button class="mini danger" data-delete-user="${safe(u.id)}" ${u.id==='admin'?'disabled':''}>삭제</button></td></tr>`).join('')}</tbody></table>`; }
function saveUser(){ const name=$('adminUserName').value.trim(), id=norm($('adminUserId').value), phone=$('adminUserPhone').value.trim(), password=$('adminUserPw').value.trim(), role=$('adminUserRole').value; if(!name||!id||!password) return alert('이름, 아이디, 비밀번호를 입력하세요.'); const dup=users.find(u=>norm(u.id)===id); if(editingUserId){ if(editingUserId!==id && dup) return alert('이미 사용 중인 아이디입니다.'); const u=users.find(x=>x.id===editingUserId); Object.assign(u,{id,name,phone,password,role}); if(currentUser.id===editingUserId){currentUser={id,name,phone,role};save('currentUser',currentUser);} } else { if(dup) return alert('이미 사용 중인 아이디입니다.'); users.push({id,name,phone,password,role}); } save('users',users); clearUserForm(); render(); alert('저장되었습니다.'); }
function editUser(id){ const u=users.find(x=>x.id===id); if(!u) return; editingUserId=id; $('adminUserName').value=u.name; $('adminUserId').value=u.id; $('adminUserPhone').value=u.phone||''; $('adminUserPw').value=u.password; $('adminUserRole').value=u.role; window.scrollTo({top:0,behavior:'smooth'}); }
function deleteUser(id){ if(id==='admin') return alert('기본 관리자는 삭제할 수 없습니다.'); const u=users.find(x=>x.id===id); if(u&&confirm(`${u.name} 계정을 삭제할까요?`)){ users=users.filter(x=>x.id!==id); save('users',users); renderAdmin(); } }
function clearUserForm(){ editingUserId=''; ['adminUserName','adminUserId','adminUserPhone','adminUserPw'].forEach(id=>$(id).value=''); $('adminUserRole').value='worker'; }
window.addEventListener('error', e=>{ $('errorBox').classList.remove('hidden'); $('errorBox').textContent='오류: '+(e.message||'알 수 없는 오류'); console.error(e.error||e.message); });
window.addEventListener('DOMContentLoaded', init);
